package Games;

import Scanning.Scanning;
import java.util.Random;

//Caesar Chiffre
public class CaesarChiffre {
    public static void caesarChiffre() {
        //Random key to encrypt
        Random rnd = new Random();
        int rndNumber = rnd.nextInt(25) + 1; // From 1 to 25


        //Asking for a text to encrypt
        System.out.println("Please enter your message for encryption");
        String inputWords = Scanning.scan.nextLine();

        //Encryption
        StringBuilder codedResult = new StringBuilder(); //Generated by IntelliJ with the += (Original was #String codedResult = "";)
        for (int i = 0; i < inputWords.length(); i++) {
            char character = inputWords.charAt(i);
            //Checking if char is letter
            if (Character.isLetter(character)) {
                //Create temporary variable from character
                char tempCharacter = (char) (Character.toUpperCase(character) + rndNumber); //Enter random generated number

                if (tempCharacter > 'Z') {
                    tempCharacter = (char) (tempCharacter - 26);
                }

                if (character >= 'a') {
                    tempCharacter = (char) (tempCharacter + 32);
                }

                character = tempCharacter;
            }

            codedResult.append(character); //+=
        }

        //Print encrypt text
        System.out.println("Here is your coded Text. \nCan you find the right Key?\n");
        System.out.println("---------------------------------------------------");
        System.out.println(codedResult);
        System.out.printf("Your random key %d \n", rndNumber);
        System.out.println("---------------------------------------------------\n\n");


        StringBuilder encodedResult; //Generated by IntelliJ with the += (Original was #String encodedResult;)
        //Generate number 25 to 1
        for (int i = 25; i >= 1; i--) { //From 25 to 01
            encodedResult = new StringBuilder(); //Generated by IntelliJ with the += (Original was #encodedResult = "";)

            //Decryption
            int key; //To use it outside
            for (key = 0; key < codedResult.length(); key++) {
                char character = codedResult.charAt(key);
                //Checking if char is letter
                if (Character.isLetter(character)) {
                    //Create temporary variable from character
                    char tempCharacter = (char) (Character.toUpperCase(character) + i); //i = Enter for loop number 1-26

                    if (tempCharacter > 'Z') {
                        tempCharacter = (char) (tempCharacter - 26);
                    }

                    if (character >= 'a') {
                        tempCharacter = (char) (tempCharacter + 32);
                    }

                    character = tempCharacter;
                }

                encodedResult.append(character); //+= StringBuilder?
            }

            key = 26 - i;
            System.out.println(key + "\n" + encodedResult + "\n");
        }
    }
}
