import java.util.Random;

public class Games {

    //Game FizzBuzz
    public static void lesson5_1(){
        System.out.println("Let's play FizzBuzz.");
        boolean sayNumber;

        for(int i = 1; i < 101; i++){
            sayNumber = true;

            if (i % 3 == 0 & i % 5 == 0){
                System.out.println("FizzBuzz");
                sayNumber = false;
            }
            else if (i % 3 == 0){
                System.out.println("Fizz");
                sayNumber = false;
            }
            else if (i % 5 == 0){
                System.out.println("Buzz");
                sayNumber = false;
            }

            if (sayNumber) {
                System.out.println(i);
            }
        }
    }

    //Multiplications
    public static void lesson5_2(){
        for(int i = 1; i <= 10; i++){
            System.out.printf("times %d \n", i);
            for( int j = 1; j <= 10; j++){
                System.out.printf("%d * %d = %d \n", j, i, j * i);
            }

        }
    }

    //Caesar Chiffre
    public static void lesson5_3(){
        //Random key to encrypt
        Random rnd = new Random();
        int rndNumber = rnd.nextInt(24) + 2;

        //Asking for a text to encrypt
        System.out.println("Please enter your message for encryption");
        String inputWords = Scanning.scan.nextLine();

        //Encryption
        StringBuilder codedResult = new StringBuilder(); //Generated by IntelliJ with the += (Original was #String codedResult = "";)
        for(int i = 0; i < inputWords.length(); i++) {
            char character = inputWords.charAt(i);
            //Checking if char is letter
            if (Character.isLetter(character)) {
                //Create temporary variable from character
                char tempCharacter = (char)(Character.toUpperCase(character) + rndNumber); //Enter random generated number

                if (tempCharacter > 'Z') {
                    tempCharacter = (char)(tempCharacter - 26);
                }

                if (character >= 'a') {
                    tempCharacter = (char)(tempCharacter + 32);
                }

                character = tempCharacter;
            }

            codedResult.append(character); //+=
        }

        //Print encrypt text
        System.out.println("Here is your coded Text. \nCan you find the right Key?\n");
        System.out.println("---------------------------------------------------");
        System.out.println(codedResult);
        System.out.println("---------------------------------------------------\n\n");

        //Decryption number and text
        String encodedString;
        for(int i = 1; i <= 26; i++) {
            encodedString = "";

            //Decryption
            int searchingKey;
            for(searchingKey = 0; searchingKey < codedResult.length(); searchingKey++) {
                char character = codedResult.charAt(searchingKey);
                if (Character.isLetter(character)) {
                    char tempCharacter = (char)(Character.toUpperCase(character) + i);
                    if (tempCharacter > 'Z') {
                        tempCharacter = (char)(tempCharacter - 26);
                    }

                    if (character >= 'a') {
                        tempCharacter = (char)(tempCharacter + 32);
                    }

                    character = tempCharacter;
                }

                encodedString = encodedString + character;
            }
            searchingKey = 26 - i;
            System.out.println(searchingKey + "\n" + encodedString + "\n");
        }

    }
}

